name: Update README with Latest OpenSauced Highlight

on:
  schedule:
    - cron: '15 19 * * *' 
jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      # Fetch Latest Highlight using Axios action
      
      # Custom Script for Fetching Data & Updating README
      - name: Fetch Latest Highlight and Update README
        run: node .github/scripts/updateReadme.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Commit and Push Changes
      - name: Commit and Push if README Updated
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Updated README with the latest OpenSauced highlight" || echo "No changes to commit"
          git push
