name: Update README with Latest OpenSauced Highlight

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: 'BekahHW/BekahHW'
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  

      - name: Fetch Latest Highlight and Update README
        run: |
          npm install axios
          node updateReadme.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push if Changed
        run: |
          git config --global user.email "rhawrot@gmail.com"
          git config --global user.name "BekahHW"
          git add README.md
          git commit -m "Updated README with the latest OpenSauced highlight" || exit 0
          git push
